[package]
name = "gate-program-block-list"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18"
borsh = "0.10"
spl-tlv-account-resolution = "0.5"

[dev-dependencies]
solana-program-test = "1.18"
solana-sdk = "1.18"

